name: semantic-release-action
on:
  pull_request:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup permissions
        run: |
          cd .git
          sudo chmod -R ugo+rwX .

      - uses: codfish/semantic-release-action@v1
        id: semantic
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          dry_run: true
          branches: |
            [
              'main'
            ]
          tag_format: '${version}'
          plugins: |
            ['@semantic-release/commit-analyzer', '@semantic-release/release-notes-generator', '@semantic-release/github']

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@e6e38bacfdf1a337459f332974bb2327a31aaf4b

      - name: Set new version -> ${{ steps.semantic.outputs.release-version }}
        uses: gradle/gradle-build-action@67421db6bd0bf253fb4bd25b31ebb98943c375e1
        with:
          arguments: setVersion -PnewVersion=${{ steps.semantic.outputs.release-version }}

      - name: Build with Gradle
        uses: gradle/gradle-build-action@67421db6bd0bf253fb4bd25b31ebb98943c375e1
        with:
          arguments: build

      - name: Push new version and release tag
        uses: EndBug/add-and-commit@v9
        with:
          default_author: github_actions
          message: Release ${{ steps.semantic.outputs.release-version }}
          add: app/build.gradle.kts
          tag: ${{ steps.semantic.outputs.release-version }}
